In [12]:
import torch

In [13]:
x = torch.randn(3)
x

tensor([1.0076, 0.6568, 0.1607])

In [14]:
x = torch.randn(3, requires_grad=True)
x

tensor([-2.7685,  0.1612,  2.2742], requires_grad=True)

In [15]:
y = x + 2
y

tensor([-0.7685,  2.1612,  4.2742], grad_fn=<AddBackward0>)

In [16]:
z = y*y*2
z

tensor([ 1.1811,  9.3417, 36.5380], grad_fn=<MulBackward0>)

In [17]:
z = z.mean()
z

tensor(15.6869, grad_fn=<MeanBackward0>)

In [18]:
z.backward()  # dz/dx
print(x.grad)

tensor([-1.0246,  2.8816,  5.6990])


In [19]:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

In [20]:
x.requires_grad_(False)
x

tensor([-2.7685,  0.1612,  2.2742])

In [21]:
y = x.detach()
y

tensor([-2.7685,  0.1612,  2.2742])

In [25]:
x = torch.randn(3, requires_grad=True)
y = x+2
print(y)

tensor([1.5476, 1.9725, 1.7247], grad_fn=<AddBackward0>)


In [26]:
with torch.no_grad():
    y = x +2
    print(y)

tensor([1.5476, 1.9725, 1.7247])


In [30]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()